Send mail reminder
AT-PHPIntership/flappy-book pull request #103
Opened 2018-01-30 07:58 UTC by at-trampham

## Description
Reminder send mail for user
## Reference Requirements
- Product Backlog ID: PBI-5
- Task ID: #5.3

## Reference Isuees
Non

## Migrations
NO

## Impacted Areas in Application
List general components of the application that this PR will affect:

-

## SQL query and `explain`
Non SQL

- Refer to [Using Explain with MySQL](https://viblo.asia/p/su-dung-explain-de-toi-uu-cau-lenh-mysql-BYjv44gmvxpV)

2018-01-31 10:32 UTC, at-duongtruong reviewed
LGTM

2018-02-01 08:01 UTC, ghost requested changes

2018-02-01 08:01 UTC, at-huenguyen commented on app/Mail/ReminderedUser.php
> +        $subject = 'Reminder User Borrowing Book';
khai báo đoạn string chỗ nào đê em, hardcode

2018-02-01 08:01 UTC, at-huenguyen commented on app/Mail/ReminderedUser.php
> +        $numberDateBorrowed = (strtotime($currentDate) - strtotime($borrowDate)) / (60 * 60 * 24);
chỗ này em tìm xem có hàm hỗ trợ nào ko, sao tính tay vại :3

2018-02-05 04:52 UTC, ghost approved these changes

2018-02-05 04:52 UTC, merged