unit test add category
AT-PHPIntership/flappy-book pull request #114
Opened 2018-02-01 06:58 UTC by at-trampham

## Description
Unit test for add category
## Reference Requirements
- Product Backlog ID: Non PBI
- Task ID: Non TI

## Reference Isuees
Non

## Migrations
NO

## Impacted Areas in Application
List general components of the application that this PR will affect:

-

## SQL query and `explain`
Non

- Refer to [Using Explain with MySQL](https://viblo.asia/p/su-dung-explain-de-toi-uu-cau-lenh-mysql-BYjv44gmvxpV)

2018-02-01 10:31 UTC, at-duongtruong reviewed
LGTM

2018-02-05 03:07 UTC, ghost requested changes

2018-02-05 03:07 UTC, at-huenguyen commented on tests/Browser/Pages/Backend/Categories/AddCategoryTest.php
> +        $userId = DB::table('users')->pluck('employ_code')->toArray();
em đã tạo  mảng user đâu mà truy vấn? Đã có 1 user đc tạo ở DuskTestCase `$this->user` là lấy đc mà.

2018-02-05 03:07 UTC, at-huenguyen commented on tests/Browser/Pages/Backend/Categories/AddCategoryTest.php
> +                ->assertSee('Successfully add the "'.self::TITLE_NOT_EXIST.'" category!');
thêm space nhá `...'Successfully add the "' . self::TITLE_NOT_EXIST . '" category!'...`

2018-02-05 03:07 UTC, at-huenguyen commented on tests/Browser/Pages/Backend/Categories/AddCategoryTest.php
> +        $categoryId = DB::table('categories')->pluck('id')->toArray();
em đưa tạo category vào đây và lấy từ factory của category lun để pluck.
Mà em tạo có 1 category mà pluck làm gì?

2018-02-05 03:07 UTC, at-huenguyen commented on tests/Browser/Pages/Backend/Categories/AddCategoryTest.php
> +            factory(Book::class)->create([
em muốn test add category thì tạo book có cần thiết ko?

2018-02-05 04:54 UTC, ghost requested changes

2018-02-05 04:54 UTC, at-huenguyen commented on tests/Browser/Pages/Backend/Categories/AddCategoryTest.php
> +    const NUMBER_RECORD_BOOK = 5;
ko dùng thì bỏ biến này lun đi nha em

2018-02-05 06:43 UTC, ghost approved these changes

2018-02-05 06:44 UTC, merged