Document for api login
AT-PHPIntership/flappy-book pull request #129
Opened 2018-02-07 07:47 UTC by at-hieule

## Description
- Document for api login: 
+ Login successfully
+ Login fail
## Reference Requirements
- Product Backlog ID: PBI-52
- Task ID: #52.1

## Reference Isuees

## Migrations
NO

## Impacted Areas in Application
List general components of the application that this PR will affect:

## SQL query and `explain`
List of all queries and attach the result of each explaining query (in text, screenshot...)

2018-02-08 10:30 UTC, at-minhdao reviewed
check cmt với

2018-02-08 10:30 UTC, at-minhdao commented on docs/api-references/login.md
> +        "deleted_at": null
mình chỉ login thì đâu cần lấy trường `deleted_at` làm gì nhỉ

2018-02-08 10:54 UTC, at-minhdao reviewed
check cmt

2018-02-08 10:54 UTC, at-minhdao commented on docs/api-references/sample.md
> +    "status": "failed",
đã đồng bộ thẻ meta thì chổ này cũng nên đặt vào trong meta luôn nghe

2018-02-09 02:06 UTC, at-minhdao commented
LGTM

2018-02-09 02:14 UTC, at-duyho commented
- trong team nên define ra 2 cấu trúc response: 1 response cho trường hợp success, 1 response cho trường hợp error. không nên gộp chung 2 cấu trúc lại như nhau.

2018-02-09 07:53 UTC, ghost requested changes
check my comment

2018-02-09 07:53 UTC, at-duyho commented on docs/api-references/login.md
> +| Content-Type | form-data/json|
- what's form-data/json?

2018-02-09 07:53 UTC, at-duyho commented on docs/api-references/login.md
> +    "data": {}
-chưa đổi sang response error hả?

2018-02-09 07:53 UTC, at-duyho commented on docs/api-references/login.md
> +    "data": {
- nên mô tả cấu trúc response( name, mô tả, kiểu dữ liệu, ví dụ)

2018-03-08 01:30 UTC, ghost approved these changes
LGTM

2018-03-08 01:30 UTC, merged