Get and show data qrcode not print yet list
AT-PHPIntership/flappy-book pull request #130
Opened 2018-02-07 08:16 UTC by at-trampham

## Description
Get and show data qrcode not print yet list
## Reference Requirements
- Product Backlog ID: PBI-9
- Task ID: #9.2 & #9.3

## Reference Isuees
Non

## Migrations
NO

## Impacted Areas in Application
List general components of the application that this PR will affect:

-

## SQL query and `explain`
select count(*) as aggregate from `qrcodes` where `qrcodes`.`status` = '0'
![image](https://user-images.githubusercontent.com/33870071/35905390-82985ea4-0c19-11e8-9db0-b8d6bc1e16d7.png)

select `qrcodes`.`id`, `qrcodes`.`prefix`, `qrcodes`.`code_id` from `qrcodes` where `qrcodes`.`status` = '0' limit 10 offset 0
![image](https://user-images.githubusercontent.com/33870071/35905454-cb34c882-0c19-11e8-8adb-d8a6e341f581.png)

- Refer to [Using Explain with MySQL](https://viblo.asia/p/su-dung-explain-de-toi-uu-cau-lenh-mysql-BYjv44gmvxpV)

2018-02-21 06:56 UTC, at-duongtruong reviewed
LGTM

2018-02-21 08:58 UTC, at-xinhnguyen commented on resources/views/backend/qrcodes/index.blade.php
> +                      <td class="text-center">{{ $qrcode->prefix . sprintf(config('define.qrcodes.number_format'), $qrcode->code_id) }}</td>
dùng getAtrribute trong model thay cho đoạn này cho gọn em

2018-02-21 09:24 UTC, at-xinhnguyen commented on app/Http/Controllers/Admin/QrcodeController.php
> +use DB;
k dùng thì k cần `use`

2018-02-21 09:27 UTC, at-xinhnguyen commented on app/Http/Controllers/Admin/QrcodeController.php
> +            ->where('qrcodes.status', Qrcode::NOT_PRINT_STATUS)
a thấy table `qrcodes` có  use `softDelete`.
nếu `qrcodes` chỉ có 2 trạng thái thì sử dụng `softDelete` thay cho cái const này

2018-02-21 09:28 UTC, at-xinhnguyen commented on app/Model/Qrcode.php
> +    const NOT_PRINT_STATUS = 0;
không in: là sao Trâm

2018-02-21 09:29 UTC, ghost requested changes
Please check my cmt

2018-02-22 03:17 UTC, at-xinhnguyen commented on app/Model/Qrcode.php
> +    const QRCODE_STATUS = 0;
thường thì 0,1 thì mình nên đặt giá trị cho `active` là 1.

2018-02-22 06:48 UTC, ghost reviewed
LGTM

2018-02-22 06:48 UTC, merged