Document for API detail book
AT-PHPIntership/flappy-book pull request #139
Opened 2018-02-09 06:53 UTC by at-minhdao

## Description
A few sentences describing the overall goals of the pull request's commits.
## Reference Requirements
- Product Backlog ID: PBI-38
- Task ID: #38.1

## Migrations
NO

## Impacted Areas in Application
List general components of the application that this PR will affect:
-

## SQL query and `explain`
List of all queries and attach the result of each explaining query (in text, screenshot...)

- Non-SQL

2018-02-09 07:10 UTC, at-hieule reviewed
Please check my cmt

2018-02-09 07:10 UTC, at-hieule commented on resources/views/api-doc-builders/index.blade.php
> +
Dư dòng bạn ơi

2018-02-09 07:10 UTC, at-hieule commented on docs/api-references/book.md
> +#### Response
Response nên phân ra success và fail. Không cần `request headers` lặp lại

2018-02-09 07:33 UTC, at-hieule commented
LGTM

2018-02-09 07:49 UTC, at-duyho commented on docs/api-references/book.md
> +/api/books/{id}
- nên mô tả thông tin của response. (tên, mô tả, kiểu dữ liệu, ví dụ)

2018-02-09 07:49 UTC, ghost requested changes
check my comment

2018-02-21 04:29 UTC, at-trampham reviewed
LGTM

2018-02-21 04:30 UTC, at-trampham commented
LGTM

2018-02-21 04:34 UTC, ghost approved these changes
LGTM

2018-02-21 04:34 UTC, merged