Api detail book
AT-PHPIntership/flappy-book pull request #143
Opened 2018-02-21 04:40 UTC by at-minhdao

## Description
A few sentences describing the overall goals of the pull request's commits.
## Reference Requirements
- Product Backlog ID: PBI-38
- Task ID: #38.2

## Migrations
NO

## Impacted Areas in Application
List general components of the application that this PR will affect:
- None

## SQL query and `explain`
List of all queries and attach the result of each explaining query (in text, screenshot...)
```mysql
select `books`.`id`, `books`.`title`, `books`.`category_id`, `books`.`description`, 
           `books`.`language`, `books`.`rating`, `books`.`total_rating`, `books`.`picture`, 
           `books`.`author`, `books`.`price`, `books`.`unit`, `books`.`year`, `books`.`page_number`, 
           `borrows`.`status`, `users`.`id` as `user_id`, `users`.`name` as `donator` from `books` 
left join `borrows` on `books`.`id` = `borrows`.`book_id` 
inner join `users` on `books`.`from_person` = `users`.`employ_code` 
where `books`.`id` = '171' and `books`.`deleted_at` is null 
order by `borrows`.`created_at` desc limit 1
```
```
*************************** 1. row ***************************
           id: 1
  select_type: SIMPLE
        table: NULL
   partitions: NULL
         type: NULL
possible_keys: NULL
          key: NULL
      key_len: NULL
          ref: NULL
         rows: NULL
     filtered: NULL
        Extra: no matching row in const table
```
- Refer to [Using Explain with MySQL](https://viblo.asia/p/su-dung-explain-de-toi-uu-cau-lenh-mysql-BYjv44gmvxpV)

2018-02-22 01:18 UTC, at-hieule commented
Description  trong PR làm gì vậy?

2018-02-22 01:39 UTC, at-hieule reviewed
please check my cmt

2018-02-22 01:39 UTC, at-hieule commented on routes/api.php
> +Route::get('books/{book}', 'Api\BookController@show');
Nên cho `api` vào `namespace` lun hì

2018-02-22 02:28 UTC, at-hieule commented
OK

2018-02-22 03:30 UTC, at-duyho commented on app/Exceptions/Handler.php
> +                        'code' => 404,
- you should use Response::HttpNotfound

2018-02-22 03:30 UTC, at-duyho commented on app/Exceptions/Handler.php
> +                        'status' => 'failed',
- message should define in language file

2018-02-22 03:31 UTC, at-duyho commented on app/Exceptions/Handler.php
> +                        'message' => 'Page not found!',
message should define in language file

2018-02-22 03:34 UTC, ghost requested changes
- check my comment.
- check query explain. You miss some query and why explain type is null?

2018-02-22 10:32 UTC, at-duyho commented on app/Http/Controllers/Api/BookController.php
> +            $book->picture = url('/').'/'.config('define.books.folder_store_books').$book->picture;
- nên dùng setPictureAttribute function trong model.

2018-02-22 10:33 UTC, ghost requested changes
- check my comment

2018-02-23 09:38 UTC, ghost approved these changes
LGTM

2018-02-23 09:39 UTC, merged