Document for information of user
AT-PHPIntership/flappy-book pull request #148
Opened 2018-02-22 04:02 UTC by at-minhdao

## Description
API get information of user
## Reference Requirements
- Product Backlog ID: PBI-46
- Task ID: #46.1

## Migrations
NO

## Impacted Areas in Application
List general components of the application that this PR will affect:

-

## SQL query and `explain`
List of all queries and attach the result of each explaining query (in text, screenshot...)

- Refer to [Using Explain with MySQL](https://viblo.asia/p/su-dung-explain-de-toi-uu-cau-lenh-mysql-BYjv44gmvxpV)

2018-02-22 07:47 UTC, at-hieule commented on docs/api-references/user.md
> +### `GET` donate and borrow
Get infor user chớ

2018-02-22 08:29 UTC, at-hieule commented
LGTM!

2018-02-22 10:24 UTC, at-duyho commented
- fix conflict

2018-02-23 03:44 UTC, ghost approved these changes
LGTM

2018-02-23 03:45 UTC, at-duyho commented on docs/api-references/user.md
> +/api/users/{id}
- api này là lấy thông tin của chính user đang login hay lấy thông tin của user khác?

2018-02-23 03:45 UTC, ghost requested changes
check my comment.

2018-02-23 03:56 UTC, at-minhdao commented on docs/api-references/user.md
> +/api/users/{id}
lấy thông tin của mỗi user đó anh.
kiểu như vào trang của ai thì thấy thông tin của người đó á

2018-02-23 06:35 UTC, ghost approved these changes
LGTM

2018-02-23 06:35 UTC, merged