api get info user
AT-PHPIntership/flappy-book pull request #153
Opened 2018-02-26 04:36 UTC by at-minhdao

## Description
- Implement API get information of user
## Reference Requirements
- Product Backlog ID: PBI-46
- Task ID: #46.2

## Migrations
NO

## Impacted Areas in Application
List general components of the application that this PR will affect:
- None

## SQL query and `explain`
List of all queries and attach the result of each explaining query (in text, screenshot...)
```mysql
select `users`.`id`, `users`.`employ_code`, `users`.`name`, 
    `users`.`team`, `users`.`email`, `users`.`is_admin`, `users`.`avatar_url`, 
(SELECT books.title FROM books 
WHERE id IN (SELECT borrows.book_id FROM borrows WHERE users.id = borrows.user_id AND borrows.status = 0)) AS name_book, 
(select count(*) from `books` where `users`.`employ_code` = `books`.`from_person` and `books`.`deleted_at` is null) as `books_count`, 
(select count(*) from `borrows` where `users`.`id` = `borrows`.`user_id`) as `borrows_count` from `users` where `id` = '11' and `users`.`deleted_at` is null limit 1

```
```
*************************** 1. row ***************************
           id: 1
  select_type: PRIMARY
        table: users
   partitions: NULL
         type: const
possible_keys: PRIMARY
          key: PRIMARY
      key_len: 4
          ref: const
         rows: 1
     filtered: 100.00
        Extra: NULL
*************************** 2. row ***************************
           id: 5
  select_type: DEPENDENT SUBQUERY
        table: borrows
   partitions: NULL
         type: ref
possible_keys: borrows_user_id_foreign
          key: borrows_user_id_foreign
      key_len: 4
          ref: const
         rows: 1
     filtered: 100.00
        Extra: Using index
*************************** 3. row ***************************
           id: 4
  select_type: DEPENDENT SUBQUERY
        table: books
   partitions: NULL
         type: ref
possible_keys: books_from_person_foreign
          key: books_from_person_foreign
      key_len: 42
          ref: const
         rows: 1
     filtered: 10.00
        Extra: Using where
*************************** 4. row ***************************
           id: 2
  select_type: DEPENDENT SUBQUERY
        table: borrows
   partitions: NULL
         type: ref
possible_keys: borrows_book_id_foreign,borrows_user_id_foreign
          key: borrows_user_id_foreign
      key_len: 4
          ref: const
         rows: 1
     filtered: 10.00
        Extra: Using where; Start temporary
*************************** 5. row ***************************
           id: 2
  select_type: DEPENDENT SUBQUERY
        table: books
   partitions: NULL
         type: eq_ref
possible_keys: PRIMARY
          key: PRIMARY
      key_len: 4
          ref: homestead.borrows.book_id
         rows: 1
     filtered: 100.00
        Extra: End temporary
```
- Refer to [Using Explain with MySQL](https://viblo.asia/p/su-dung-explain-de-toi-uu-cau-lenh-mysql-BYjv44gmvxpV)

2018-02-26 07:21 UTC, at-trampham reviewed
LGTM

2018-02-26 09:21 UTC, at-duyho commented on app/Http/Controllers/Api/UserController.php
> +            DB::raw("(SELECT books.title FROM books WHERE id IN (SELECT borrows.book_id FROM borrows WHERE users.id = borrows.user_id AND borrows.status = " . Borrow::BORROWING . ")) AS book_borrowin
- trong trường hợp 1 user mượn nhiều sách thì data trả về sẽ như thế nào?

2018-02-26 09:21 UTC, ghost requested changes
check my comment

2018-02-26 09:31 UTC, at-minhdao commented on app/Http/Controllers/Api/UserController.php
> +            DB::raw("(SELECT books.title FROM books WHERE id IN (SELECT borrows.book_id FROM borrows WHERE users.id = borrows.user_id AND borrows.status = " . Borrow::BORROWING . ")) AS book_borrowin
- theo như bên yêu cầu thì với mỗi user thì trong 1 lần chỉ được được mượn 1 cuốn sách thôi anh
- muốn mượn quyển khác thì phải trả quyển đang mượn trước.
- nên chổ đó chỉ lấy ra thông tin cuốn sách mà user đó đang mượn, hoặc là có sách, hoặc là `null`

2018-02-28 02:17 UTC, ghost approved these changes
LGTM

2018-02-28 02:17 UTC, merged