document get top 10 books review
AT-PHPIntership/flappy-book pull request #157
Opened 2018-02-27 03:49 UTC by at-minhdao

## Description
- Get top 10 books review. With image, book name and score review
## Reference Requirements
- Product Backlog ID: PBI-35
- Task ID: #35.1

## Migrations
NO

## Impacted Areas in Application
List general components of the application that this PR will affect:
- None

## SQL query and `explain`
List of all queries and attach the result of each explaining query (in text, screenshot...)

- Refer to [Using Explain with MySQL](https://viblo.asia/p/su-dung-explain-de-toi-uu-cau-lenh-mysql-BYjv44gmvxpV)

2018-02-27 07:25 UTC, at-trampham reviewed
LGTM

2018-02-28 02:13 UTC, at-duyho commented on docs/api-references/book.md
> +| data | Object | Object book |
- an Array or an object?

2018-02-28 02:13 UTC, ghost requested changes
check my comment!

2018-03-01 02:37 UTC, ghost approved these changes
LGTM

2018-03-01 02:37 UTC, merged