api_search_book
AT-PHPIntership/flappy-book pull request #158
Opened 2018-02-27 03:53 UTC by at-duongtruong

## Description
API search book
## Reference Requirements
- Product Backlog ID: PBI-33
- Task ID: #33.2

## Reference Isuees
#{issue_id}

## Migrations
YES

## Impacted Areas in Application
List general components of the application that this PR will affect:

-

2018-03-09 02:29 UTC, at-trampham commented on app/Service/BookService.php
> +use DB;
`use DB` ko dùng remove đi nha

2018-03-09 02:29 UTC, at-trampham commented on app/Service/BookService.php
> +                ->orderBy('books.created_at', 'DESC');
fix space lại nha

2018-03-09 03:41 UTC, at-trampham reviewed
LGTM

2018-03-12 02:21 UTC, at-duyho commented on app/Service/BookService.php
> +    public static function getBooks(Request $request = null)
- không nên dùng hàm static, sử dụng hàm khởi tạo của controller để khởi tạo đối tượng service.
- tìm hiểu thêm về Dependency injection trong laravel. https://viblo.asia/p/laravel-beauty-tim-hieu-ve-service-container-3KbvZ1wLGmWB

2018-03-12 02:21 UTC, ghost requested changes
Check my comment!

2018-03-13 01:38 UTC, at-duyho commented on app/Service/BookService.php
> +    public function getBooks(Request $request = null)
- function này sẽ luôn luôn yêu cầu đưa vào là một Request vậy nên không nên set default null.

2018-03-13 01:38 UTC, ghost requested changes
check my comment

2018-03-14 02:00 UTC, ghost approved these changes
LGTM

2018-03-14 02:00 UTC, merged