Api get top books review
AT-PHPIntership/flappy-book pull request #159
Opened 2018-02-27 05:00 UTC by at-minhdao

## Description
- Get top 10 books review. With image, book name and score review
## Reference Requirements
- Product Backlog ID: PBI-35
- Task ID: #35.2

## Reference Isuees
#{issue_id}

## Migrations
NO

## Impacted Areas in Application
List general components of the application that this PR will affect:

-

## SQL query and `explain`
List of all queries and attach the result of each explaining query (in text, screenshot...)
```
select `id`, `title`, `rating`, `total_rating`, `picture` 
from `books` 
where `books`.`deleted_at` is null 
order by `rating` desc, `total_rating` desc 
limit 10
```
```
*************************** 1. row ***************************
           id: 1
  select_type: SIMPLE
        table: books
   partitions: NULL
         type: ALL
possible_keys: NULL
          key: NULL
      key_len: NULL
          ref: NULL
         rows: 16
     filtered: 100.00
        Extra: Using filesort
```
- Refer to [Using Explain with MySQL](https://viblo.asia/p/su-dung-explain-de-toi-uu-cau-lenh-mysql-BYjv44gmvxpV)

2018-02-27 10:07 UTC, at-trampham commented on app/Http/Controllers/Api/BookController.php
> +                    ->limit(config('define.books.top_books_review'))
top book review thì nên ```orderBy``` theo số lượng review chứ nhỉ

2018-02-27 10:07 UTC, at-trampham commented on config/define.php
> +        'top_books_review' => 10,
đặt tên khác rõ ràng hơn dc ko nhỉ, ```top_books_review``` còn mơ hồ quá,này là số lượng top book mà

2018-02-27 10:08 UTC, at-trampham commented
please check my comment :)

2018-02-27 10:26 UTC, at-trampham reviewed
LGTM

2018-02-28 02:27 UTC, at-duyho commented on app/Http/Controllers/Api/BookController.php
> +        return $this->responseObject($topBooks);
- cái này trả về một collection thì dùng responseObject có đúng với format json không?

2018-02-28 02:27 UTC, ghost requested changes
check my comment

2018-03-01 01:31 UTC, ghost approved these changes
LGTM

2018-03-01 01:31 UTC, merged