validate edit book
AT-PHPIntership/flappy-book pull request #17
Opened 2018-01-04 09:10 UTC by at-longdau

## Description
Validate form edit.
## Reference Requirements
- Product Backlog ID: PBI-4
- Task ID: #4.3

## Migrations
NO

## Impacted Areas in Application
List general components of the application that this PR will affect:

-

## SQL query and `explain`
none

2018-01-04 10:44 UTC, at-minhdao commented
please check cmt and fix conflict

2018-01-08 08:09 UTC, at-minhdao commented
LGTM!

2018-01-09 04:01 UTC, ghost requested changes
A có vài comment, mọi ng chia sẻ nhau nhé! 🍡

2018-01-09 04:01 UTC, at-nhuibo commented on app/Model/Book.php
> +    const TYPE_VND = 0;
Chỗ này ở trên kia có rồi, sao dưới ni thêm nữa vậy?
Khi code mà conflict, chú ý fix sao cho ko bị lặp hoặc thiếu code nhé.
Với lại phải có thêm phần comment/description cho mấy cái constant thế này nữa...

2018-01-09 04:01 UTC, at-nhuibo commented on resources/views/backend/books/edit.blade.php
> +                          <label for="exampleInputTitle">{{ __('books.title') }}</label>
Cái thuộc tính `for` của thẻ `label` nó liên kết với `id` của thẻ `input`, nó phải trùng nhau, fix tất cả nhé:
1. Nếu đã có thuộc tính `for` trong thẻ `label` thì thẻ `input` tương ứng phải có `id` là giá trị của thuộc tính `for` nhé.
2. Có dùng `for` trong `label` thì phải liên kết với `id` của `input` tương ứng, không có liên kết thì remove nhé.
3. Ưu tiên phương án 1 

***Từng ký tự, kể cả dấu cách, dấu tab (convention) trong code phải hữu ích, ko thiếu, ko dư thừa. :D***
Mọi người chú ý nhé. Trước anh nhắc phần này rồi thì phải.

2018-01-09 04:01 UTC, at-nhuibo commented on resources/views/backend/books/edit.blade.php
> +                </div>
Thẻ đóng div ở trên với thẻ mở div ở dưới cùng cấp, phải để ngang hàng|cột (indent) á. 🗡
Dấu tab chỗ này bị dư nhé.

2018-01-09 09:38 UTC, at-nhuibo commented on app/Model/Book.php
> +    /**
Thêm 1 dấu xuống dòng trước comment/description nhiều dòng nha, cho code nó đẹp, dễ đọc, review.
Thêm cái type nữa nhỉ.

2018-01-09 10:05 UTC, ghost approved these changes
LGTM. Thanks.

2018-01-09 10:05 UTC, merged