Document get books of user donated
AT-PHPIntership/flappy-book pull request #178
Opened 2018-03-02 03:59 UTC by at-minhdao

## Description
- Document get books of user donated
## Reference Requirements
- Product Backlog ID: None
- Task ID: None

## Migrations
NO

## Impacted Areas in Application
List general components of the application that this PR will affect:
- None

## SQL query and `explain`
List of all queries and attach the result of each explaining query (in text, screenshot...)
- Non-SQL
- Refer to [Using Explain with MySQL](https://viblo.asia/p/su-dung-explain-de-toi-uu-cau-lenh-mysql-BYjv44gmvxpV)

2018-03-02 06:50 UTC, at-trampham reviewed
LGTM

2018-03-02 07:17 UTC, at-duyho commented on docs/api-references/user.md
> +/api/users/{id}/donated
- api này lấy cho chính nó hay cho user khác.

2018-03-02 07:18 UTC, ghost requested changes
-check my comment

2018-03-02 08:56 UTC, at-minhdao commented on docs/api-references/user.md
> +/api/users/{id}/donated
- với mỗi người dùng đã login thì có thể vào trang cá nhân người khác để xem số mà sách mà người đó đã mượn á anh :D

2018-03-05 02:51 UTC, ghost approved these changes
LGTM

2018-03-05 02:51 UTC, merged