Document for api delete comments
AT-PHPIntership/flappy-book pull request #206
Opened 2018-03-12 07:44 UTC by at-minhdao

## Description
A few sentences describing the overall goals of the pull request's commits.
## Reference Requirements
- Product Backlog ID: PBI-None
- Task ID: TI-None

## Reference Isuees
#{issue_id}

## Migrations
NO

## Impacted Areas in Application
List general components of the application that this PR will affect:

-

## SQL query and `explain`
List of all queries and attach the result of each explaining query (in text, screenshot...)
- Non-SQL
- Refer to [Using Explain with MySQL](https://viblo.asia/p/su-dung-explain-de-toi-uu-cau-lenh-mysql-BYjv44gmvxpV)

2018-03-12 08:32 UTC, at-trampham reviewed
LGTM

2018-03-13 01:43 UTC, at-duyho commented on docs/api-references/comment.md
> +```
- trường hợp fail đâu?

2018-03-13 01:43 UTC, ghost requested changes
check my comment

2018-03-14 02:53 UTC, ghost approved these changes
LGTM

2018-03-14 03:14 UTC, merged