Get list category edit book
AT-PHPIntership/flappy-book pull request #28
Opened 2018-01-08 09:36 UTC by at-longdau

## Description
Get list category form edit book.
## Reference Requirements
- Product Backlog ID: PBI-4
- Task ID: #4.4

## Migrations
YES

## Impacted Areas in Application
none

## SQL query and `explain`

2018-01-10 01:52 UTC, at-minhdao commented
please check my comment

2018-01-10 01:53 UTC, at-minhdao commented on app/Http/Controllers/Admin/BookController.php
> +        $categoryFields = [
chổ ni thì bọn mình đã thống nhất với tên là $fields rồi mà nhỉ
sửa lại nhé :)))

2018-01-10 01:53 UTC, at-minhdao commented on resources/views/backend/books/edit.blade.php
> +                        <input type="text" class="form-control" name="title" id="exampleInputTitle" placeholder="{{ __('books.Title') }}" value="{{ $book->title }}">
- phần multilanguage của placeholder books.Title phải là books.title
- tương tự cho các phần dưới nữa nhé

2018-01-10 01:53 UTC, at-minhdao commented on resources/views/backend/books/edit.blade.php
> +                        @foreach($categories as $category)
đoạn này chỉnh tab lại xí a, nhìn ko đều

2018-01-10 01:53 UTC, at-minhdao commented on resources/views/backend/books/edit.blade.php
> +                          @if($unit == $book->unit)
if là con của for nên tab nó vô trong tí

2018-01-10 03:23 UTC, at-minhdao commented
LGTM

2018-01-10 04:16 UTC, ghost requested changes
Check commet nhé...

2018-01-10 04:16 UTC, at-nhuibo commented on app/Http/Controllers/Admin/BookController.php
> +        $fields = [
Cái này thiếu 1 dấu cách đằng trước hay sao á, thấy ko thẳng hàng với mấy cái dưới.
Check sao cho nó đủ 1 tab hỷ.

2018-01-10 04:16 UTC, at-nhuibo commented on resources/views/backend/books/edit.blade.php
> +                        <input type="text" class="form-control" name="title" id="exampleInputTitle" placeholder="{{ __('books.title') }}" value="{{ $book->title }}">
A xin lỗi mọi người, bữa trước a review ko kỹ, remove cái chữ `example` trong tất cả mấy cái `for` và `id` của thẻ `label` và `input` nha.
Vì app này mình làm là thật, không phải là demo, nên không để `example`.

2018-01-10 04:16 UTC, at-nhuibo commented on resources/views/backend/books/edit.blade.php
> +                <input type="file" name="picture" id="exampleInputFile" value="{{ $book->picture }}">
Chỗ này thì ng dùng ko biết ảnh đã được upload hay chưa, vì nó ko show ra ảnh.
Mọi ng làm ri nhé:
- 1 thẻ `img` để hiển thị image đã upload => Để họ biết cái hình họ đã upload trông thế nào
- Ẩn cái input file đi
- 1 button `Change`, dùng để đổi ảnh khác
  + Khi họ click nó thì kích hoạt sự kiện click cho input file ẩn trên kia luôn => chọn file
  + Cho hiển thị cái image vừa chọn ở thẻ `img` phía trên (tham khảo: https://stackoverflow.com/questions/4459379/preview-an-image-before-it-is-uploaded)

2018-01-16 01:51 UTC, ghost approved these changes
LGTM. Thanks.

2018-01-16 01:51 UTC, merged