Sortbook addlink
AT-PHPIntership/flappy-book pull request #32
Opened 2018-01-08 15:09 UTC by at-caonguyen

## Description
Edit attribute for sort button, add javascript for event click button sort
## Reference Requirements
- Product Backlog ID: PBI-7
- Task ID: #7.1

## Migrations
NO

## Impacted Areas in Application
List general components of the application that this PR will affect:
- resources/lang/en/books.php
- public/js/main.js

## SQL query and `explain`
List of all queries and attach the result of each explaining query (in text, screenshot...)
NO

2018-01-09 02:49 UTC, at-nhannguyen2 commented
LGTM

2018-01-09 06:10 UTC, ghost requested changes
check cmt nha em

2018-01-09 06:10 UTC, at-huenguyen commented on public/js/main.js
> +        $(this).children().attr('class', 'fa fa-sort-amount-desc');
có cần `fa` vào nữa ko em?

2018-01-09 06:10 UTC, at-huenguyen commented on public/js/main.js
> +    if(filter == $(this).attr('name')) {
lệnh này nếu ko cần có được ko?

2018-01-09 06:10 UTC, at-huenguyen commented on public/js/main.js
> +        $(this).children().attr('class', 'fa fa-sort-amount-desc');
sao ko thấy set lại `order` là `asc` ở đây?

2018-01-09 17:29 UTC, at-huenguyen commented on public/js/main.js
> +      } else if (order == 'asc'){
giá trị của order sẽ chỉ có 2 trạng thái `desc` và `asc` thì đã else rồi thì cần if chỗ này nữa ko?

2018-01-10 01:12 UTC, at-caonguyen commented on public/js/main.js
> +        $(this).children().attr('class', 'fa fa-sort-amount-desc');
Dạ tại có sẵn link rồi nên khi là asc thì em mới sửa thôi, còn lúc là desc thì em giữ nguyên vẫn được

2018-01-10 01:14 UTC, at-caonguyen commented on public/js/main.js
> +      } else if (order == 'asc'){
dạ để em sửa ạ

2018-01-10 01:41 UTC, at-huenguyen commented on public/js/main.js
> +        $(this).children().attr('class', 'fa fa-sort-amount-desc');
nếu em giữ nguyên thì cái icon nó ko đúng như mình muốn đó

2018-01-10 03:24 UTC, at-huenguyen commented on public/js/main.js
> +               $(this).attr('href', url);
thêm 1 space nữa nè em :smile:

2018-01-10 03:47 UTC, ghost approved these changes
LGTM

2018-01-10 03:47 UTC, merged