Middleware admin login
AT-PHPIntership/flappy-book pull request #36
Opened 2018-01-09 09:07 UTC by at-hieule

## Description
- Middleware admin login.
## Reference Requirements
- Product Backlog ID: PBI-1
- Task ID: 1.3

## Migrations
NO

## Impacted Areas in Application
List general components of the application that this PR will affect:

-

## SQL query and `explain`
List of all queries and attach the result of each explaining query (in text, screenshot...)

- Non

2018-01-09 10:04 UTC, at-longdau commented
LGTM

2018-01-09 10:17 UTC, ghost requested changes
Check comment và fix nhé! ;)

2018-01-09 10:17 UTC, at-nhuibo commented on app/Http/Middleware/AdminLoginMiddleware.php
> +            }
Nếu đã đăng nhập rồi thì đưa ra thông báo lỗi `Quyền truy cập bị từ chối.` nhé.
Sau đó chuyển sang trang profile của users.
Chứ user đã đăng nhập rồi thì không được chuyển sang trang login nữa.

2018-01-09 10:17 UTC, at-nhuibo commented on routes/web.php
> +Route::group(['namespace'=>'Admin', 'prefix'=>'admin' , 'middleware'=>'admin'], function(){
Chỗ dấu `=>` trong mảng á, thêm 1 dấu cách trước và sau nó nhé.
**Chứ để dính thế này thì rối lắm, khó nhìn, khó review và ko đúng convention nữa**, share nhau cái ni hỷ.

2018-01-10 01:39 UTC, ghost requested changes
Check lại giúp với...

2018-01-10 01:39 UTC, at-nhuibo commented on app/Http/Middleware/AdminLoginMiddleware.php
> +            abort(403, "You don't have permission to access / on this server");
Luôn luôn nhớ là phải có `trans(...)` nha, check ở phần dưới nữa ;)

2018-01-10 01:39 UTC, at-nhuibo commented on resources/views/errors/403.blade.php
> +  <p>{{ $exception->getMessage() }}</p>
Thêm 2 cái link để :
1. Về trang chủ
2. Quay lại trang họ truy cập trước đó
Cái error message cho nó đỏ rực lên nhé, cảnh báo mà.

2018-01-10 04:34 UTC, ghost approved these changes
LGTM. Thanks.

2018-01-10 04:34 UTC, merged