Save data form edit book
AT-PHPIntership/flappy-book pull request #60
Opened 2018-01-17 09:31 UTC by at-longdau

## Description
Save data form edit book
## Reference Requirements
- Product Backlog ID: PBI-4
- Task ID: #4.5

## Reference Isuees
#{issue_id}

## Migrations
 NO

## Impacted Areas in Application
app/Http/Controllers/Admin/BookController.php
config/image.php
resources/views/backend/books/edit.blade.php
resources/views/backend/books/index.blade.php
-

## SQL query and `explain`
![screenshot from 2018-01-17 16-26-14](https://user-images.githubusercontent.com/33889915/35035399-cf5b6b2c-fba3-11e7-8fa0-0d2beeeb0079.png)
![screenshot from 2018-01-17 16-27-07](https://user-images.githubusercontent.com/33889915/35035403-d2cff19c-fba3-11e7-9467-3e53976ffa3a.png)
![screenshot from 2018-01-17 16-28-48](https://user-images.githubusercontent.com/33889915/35035405-d5c31b04-fba3-11e7-947e-7772ce81ec9b.png)

2018-01-18 02:43 UTC, at-minhdao commented
please check my cmt

2018-01-18 02:52 UTC, at-minhdao commented on config/image.php
> +	];
convention sai
- end line
- tab size

2018-01-18 02:52 UTC, at-minhdao commented on resources/views/backend/books/edit.blade.php
> +    @endif
dùng laracast flash rồi thì đoạn display thông báo này chỉ cần @include('flash::message') là dc

2018-01-18 02:52 UTC, at-minhdao commented on resources/views/backend/books/index.blade.php
> +    @endif
tương tự cho laracast flash chổ này

2018-01-18 02:52 UTC, at-minhdao commented on app/Http/Controllers/Admin/BookController.php
> +            return redirect()->route('books.index');
phần thông báo nên dùng laracast flash cho tiện
ví dụ : flash(__('books.delete_book_success'))->success();
với dùng redirect()->back() để có thể trở lại trang trước với đúng phân trang

2018-01-18 04:19 UTC, at-minhdao commented
LGTM

2018-01-18 05:18 UTC, ghost requested changes
Check comment của a nhé!

2018-01-18 05:18 UTC, at-nhuibo commented on app/Http/Controllers/Admin/BookController.php
> +            $oldPath = $book->picture;
Đoạn upload và xoá ảnh cũ này viết 1 class dùng chung nhé: `app/Libraries/Image.php`.
Viết 1 method ri nhé: `updateImage($imgFile, $imgPath, $oldImg)`, cho nó return `$newPath` thôi.
Sau đó gọi mà dùng.

2018-01-18 05:18 UTC, at-nhuibo commented on app/Http/Controllers/Admin/BookController.php
> +        $user = User::where('employ_code', $request->iddonator)->first();
*Nên chia nhỏ đoạn code thành nhiều phần, mỗi phần là 1 chức năng nhỏ - nhỏ nhất có thể*.
=> Đoạn lưu data này nên viết 1 method riêng, tên `updateBook($request)`, ở dưới `if ($this->updateBook($request)) {...}`, cho cái hàm nó gọn lẹ.

2018-01-19 10:50 UTC, ghost approved these changes
LGTM. Thanks.

2018-01-23 02:37 UTC, merged