Createbook unittest
AT-PHPIntership/flappy-book pull request #76
Opened 2018-01-23 07:20 UTC by at-caonguyen

## Description
Unit test for create book.
## Reference Requirements
- Product Backlog ID: PBI-3
- Task ID: #3.5

## Reference Isuees
#{issue_id}

## Migrations
NO

## Impacted Areas in Application
List general components of the application that this PR will affect:

- No

## SQL query and `explain`
List of all queries and attach the result of each explaining query (in text, screenshot...)

2018-01-24 09:03 UTC, at-nhannguyen2 commented
LGTM

2018-01-30 07:19 UTC, at-huenguyen commented on tests/Browser/Pages/Backend/Books/AdminCreateBookTest.php
> +        $this->user = $this->createAdminUser();
remove này đi nhá

2018-01-30 07:19 UTC, at-huenguyen commented on tests/Browser/Pages/Backend/Books/AdminCreateBookTest.php
> +                    ->type('from_person', 'ATI0284')
nhìn vào làm sao biết được có tồn tại employee code này, em nên đặt biến hằng ở ngoài rồi sử dụng cho makeData và dùng tại đây. Hoặc lấy từ makeData cũng đc

2018-01-30 07:19 UTC, at-huenguyen commented on tests/Browser/Pages/Backend/Books/AdminCreateBookTest.php
> +        factory(Category::class, $row)->create();
em tạo ra category rồi dùng chỗ nào hè?

2018-01-31 07:38 UTC, ghost requested changes

2018-02-01 04:16 UTC, ghost approved these changes
LGTM

2018-02-01 04:16 UTC, merged