Search borrow
AT-PHPIntership/flappy-book pull request #86
Opened 2018-01-25 04:56 UTC by at-duongtruong

## Description
A few sentences describing the overall goals of the pull request's commits.
## Reference Requirements
- Product Backlog ID: PBI-4
- Task ID: #4.2

## Migrations
YES

## SQL query and `explain`
List of all queries and attach the result of each explaining query (in text, screenshot...)
select count(*) as aggregate from `borrows` left join `books` on `books`.`id` = `borrows`.`book_id` left join `users` on `users`.`id` = `borrows`.`user_id` where `name` LIKE '%Ms%' and `borrows`.`status` = '0'
![40](https://user-images.githubusercontent.com/33858407/35371332-1200c670-01c6-11e8-983a-257dbaa0b716.png)
select `users`.`employ_code`, `users`.`name`, `users`.`email`, `books`.`title`, `borrows`.`from_date`, `borrows`.`to_date`, `borrows`.`id` from `borrows` left join `books` on `books`.`id` = `borrows`.`book_id` left join `users` on `users`.`id` = `borrows`.`user_id` where `name` LIKE '%Ms%' and `borrows`.`status` = '0' order by `from_date` desc limit 10 offset 0
![41](https://user-images.githubusercontent.com/33858407/35371365-3ed693fa-01c6-11e8-830e-c3a502367c9a.png)
select count(*) as aggregate from `borrows` left join `books` on `books`.`id` = `borrows`.`book_id` left join `users` on `users`.`id` = `borrows`.`user_id` where `title` LIKE '%Mr%' and `borrows`.`status` = '0'
![42](https://user-images.githubusercontent.com/33858407/35371425-9565f4e0-01c6-11e8-937c-45c969850f68.png)
select `users`.`employ_code`, `users`.`name`, `users`.`email`, `books`.`title`, `borrows`.`from_date`, `borrows`.`to_date`, `borrows`.`id` from `borrows` left join `books` on `books`.`id` = `borrows`.`book_id` left join `users` on `users`.`id` = `borrows`.`user_id` where `title` LIKE '%Mr%' and `borrows`.`status` = '0' order by `from_date` desc limit 10 offset 0
![43](https://user-images.githubusercontent.com/33858407/35371455-ceddbf96-01c6-11e8-98d2-b2a4b1424b55.png)

- Refer to [Using Explain with MySQL](https://viblo.asia/p/su-dung-explain-de-toi-uu-cau-lenh-mysql-BYjv44gmvxpV)

2018-01-25 06:33 UTC, at-trampham commented on resources/lang/en/borrows.php
>  ];
LGTM

2018-01-25 08:01 UTC, ghost requested changes

2018-01-25 08:01 UTC, at-huenguyen commented on app/Http/Controllers/Admin/BorrowController.php
> +        ->select($fields)
lùi vào 4 spaces nữa nha em

2018-01-25 16:28 UTC, ghost requested changes
Em dùng đầu mà lắm câu query ở phần description vại, trong khi trong code thì có 1 câu truy vấn mà

2018-01-25 16:28 UTC, at-huenguyen commented on app/Model/Borrow.php
> +    protected $searchableFields = [
em tạo ra cái này để làm gì? và em dùng ở đâu vại?

2018-01-30 03:43 UTC, ghost approved these changes

2018-01-30 03:43 UTC, merged