Edit Book Layout
AT-PHPIntership/flappy-book pull request #9
Opened 2018-01-02 12:13 UTC by at-longdau

## Description
A few sentences describing the overall goals of the pull request's commits.
## Reference Requirements
- Product Backlog ID: PBI-1
- Task ID: TI-1

## Migrations
YES | NO

## Impacted Areas in Application
List general components of the application that this PR will affect:

-

## SQL query and `explain`
List of all queries and attach the result of each explaining query (in text, screenshot...)

- Refer to [Using Explain with MySQL](https://viblo.asia/p/su-dung-explain-de-toi-uu-cau-lenh-mysql-BYjv44gmvxpV)

2018-01-03 03:53 UTC, at-minhdao commented on routes/web.php
> +});
Phần route này nên nhóm lại theo group để dễ quản lý nhé a!
Trên slack có gởi 1 đoạn code mẫu, a vào xem

2018-01-03 03:53 UTC, at-minhdao commented on resources/views/backend/books/edit.blade.php
> +    Dashboard
những cái text này anh nên để vào transaction để sau này có thể dùng lại, và khi update thì dễ dàng hơn, không nên hardcode như vậy.
anh xem thêm ở đây nhé
https://laravel.com/docs/5.2/localization

2018-01-03 03:58 UTC, at-minhdao commented on resources/views/backend/books/edit.blade.php
> +                        <label for="exampleInputEmail1">Price</label>
mấy cái title ni cũng dùng localization nhé a

2018-01-03 03:58 UTC, at-minhdao commented on resources/views/backend/books/edit.blade.php
> +                        <textarea type="textarea" class="form-control" name="description" placeholder="Description"> </textarea>
tích hợp thêm editor nữa nghe a

2018-01-03 03:58 UTC, at-minhdao commented on resources/views/backend/books/edit.blade.php
> +                      <input type="text" class="form-control" id="exampleInputEmail1" placeholder="QR Code">
QR Code tự sinh ra nên không nhập

2018-01-03 14:04 UTC, at-minhdao commented
LGTM!

2018-01-04 03:53 UTC, ghost requested changes
Hì, 2 cái comment nha.

2018-01-04 03:53 UTC, at-nhuibo commented on resources/views/backend/books/edit.blade.php
> +                        <input type="text" class="form-control" name="title" placeholder="{{ __('Title') }}">
Chú ý `for="inputTitle"` trong label nha, `inputTitle` là ID của input mà label đó đại diện. trong input title nên có 1 cái là `id="inputTitle"` nữa.
Khi mình click vào label (chữ title) => nó sẽ focus vào input để mình nhận data.
==> Mục đích là tránh thừa code, thừa kí tự => trong code php á, dư 1 dấu cách cũng ko được chấp nhận đó nha. :D

Sửa mấy cái ở dưới nữa hỷ! ;)

2018-01-04 03:53 UTC, at-nhuibo commented on resources/views/backend/books/edit.blade.php
> +                        <input type="text" class="form-control" name="iddonator" placeholder="{{ __('ID Donator') }}">
Cái name á, trong DB column lưu tên j thì mình đặt giá trị cái đó, ko nên mỗi đằng 1 nẻo.

2018-01-04 05:06 UTC, ghost approved these changes
LGTM. Thanks.

2018-01-04 05:06 UTC, merged