List show data posts
AT-PHPIntership/flappy-book pull request #93
Opened 2018-01-26 03:27 UTC by at-duongtruong

## Description
List and show data posts
## Reference Requirements
- Product Backlog ID: PBI-9
- Task ID: #9.2

## Migrations
YES 

## SQL query and `explain`
List of all queries and attach the result of each explaining query (in text, screenshot...)
select count(*) as aggregate from `posts` left join `users` on `posts`.`user_id` = `users`.`id`
![50](https://user-images.githubusercontent.com/33858407/35423932-383cb2be-0283-11e8-9e44-949241dbc556.png)
select `posts`.`id`, `users`.`name`, `posts`.`status`, `posts`.`content`, `posts`.`created_at`, (select count(*) from `comments` where `posts`.`id` = `comments`.`commentable_id` and `comments`.`commentable_type` = 'post') as `comments_count` from `posts` left join `users` on `posts`.`user_id` = `users`.`id` limit 10 offset 0
![51](https://user-images.githubusercontent.com/33858407/35423962-5f795ff8-0283-11e8-9e4e-ee625cd7b2b9.png)

- Refer to [Using Explain with MySQL](https://viblo.asia/p/su-dung-explain-de-toi-uu-cau-lenh-mysql-BYjv44gmvxpV)

2018-01-30 09:52 UTC, at-trampham commented on resources/views/backend/posts/index.blade.php
> +                      <td class="text-center">{{ date('H:A d/m/Y', strtotime($post->created_at)) }}</td>
`H:A d/m/Y` anh khai báo trong config->define rồi gọi ra để tránh hard code nha anh,nên đổi `d/m/Y` thành `d-m-Y` cho dễ nhìn

2018-01-30 09:52 UTC, at-trampham commented on app/Model/Post.php
> +    const REVIEW_TYPE = 0;
sửa thành 
`const TYPE_STATUS = 0` 
`const TYPE_FIND_BOOK = 1` 
`const TYPE_REVIEW_BOOK = 2` 
cho đồng bộ nha anh,do bên detail Post đặt như ri rồi,sau đỡ conflict,với anh để sai giá trị 0,1,2 của trạng thái,trong DB có comment `status` của `posts` table đó anh

2018-01-30 09:52 UTC, at-trampham commented on resources/views/backend/posts/index.blade.php
> +                      <td>{!! \Illuminate\Support\Str::words($post->content, 7,'...')  !!}</td>
e nghĩ số `7` này a ko nên hard code như này,define ra dùng anh

2018-01-30 10:36 UTC, at-trampham commented on app/Model/Post.php
> +     * Value of review post
sửa comment luôn anh ơi :D

2018-01-31 02:23 UTC, at-trampham commented on config/define.php
> +        'size_short_content' => '6',
số thì ko cần `'6'` đâu anh,bỏ dấu nháy đi anh

2018-01-31 03:24 UTC, at-trampham reviewed
LGTM

2018-01-31 09:05 UTC, at-huenguyen commented on resources/views/backend/posts/index.blade.php
> +                          @case(App\Model\Post::TYPE_REVIEW_BOOK)
`App\Model\Post::TYPE_REVIEW_BOOK` cũng nên bỏ vào config đê em, rồi gọi ra đây

2018-01-31 10:02 UTC, ghost requested changes

2018-01-31 10:02 UTC, at-huenguyen commented on app/Model/Post.php
> +
sao có line chỗ này? remove đi nha em, ở dưới nữa nha

2018-01-31 10:02 UTC, at-huenguyen commented on app/Model/Post.php
>      /**
thêm 1 line chỗ này nhá

2018-01-31 10:28 UTC, ghost approved these changes

2018-01-31 10:28 UTC, merged