Unitest list posts
AT-PHPIntership/flappy-book pull request #98
Opened 2018-01-29 07:10 UTC by at-duongtruong

## Description
Unitest list posts
## Reference Requirements
- Product Backlog ID: PBI-9
- Task ID: #9.3
## Migrations
NO

## Impacted Areas in Application
List general components of the application that this PR will affect:

-

2018-02-01 10:11 UTC, at-trampham reviewed
LGTM

2018-02-04 17:39 UTC, ghost requested changes

2018-02-04 17:39 UTC, at-huenguyen commented on tests/Browser/Pages/Backend/Posts/AdminListPosts.php
> +            $paginate_element = $browser->elements('.pagination li');
đặt tên biến theo kiểu camel nha em, nên sẽ là `$paginateElement`

2018-02-04 17:39 UTC, at-huenguyen commented on tests/Browser/Pages/Backend/Posts/AdminListPosts.php
> +            $number_page = count($paginate_element) - 2;
đổi biến là `$numberPage`, bị sai convention

2018-02-04 17:39 UTC, at-huenguyen commented on tests/Browser/Pages/Backend/Posts/AdminListPosts.php
> +        $userId = DB::table('users')->pluck('id')->toArray();
em có lấy `$userId` ở hàng 129 rồi mà, sao lại lấy ở đây nữa, remove đi nhá

2018-02-04 17:39 UTC, at-huenguyen commented on tests/Browser/Pages/Backend/Posts/AdminListPosts.php
> +            $books[] = factory(Book::class)->create([
`$books` đâu có đc sử dụng đâu mà đặt biến để làm gì vại em?
Và em tạo ra book để làm gì, có cần thiết ko?
Còn bảng `comment` cho `post` ko được tạo hè?

2018-02-04 17:39 UTC, at-huenguyen commented on tests/Browser/Pages/Backend/Posts/AdminListPosts.php
> +            $this->assertTrue($number_page == ceil((self::NUMBER_RECORD_CREATE + 1) / (config('define.posts.limit_rows'))));
tại sao lại `+ 1` cho `self::NUMBER_RECORD_CREATE`. Ở hàm makeData chỉ tạo đc `self::NUMBER_RECORD_CREATE` post thôi mà.
Và, ko cần ngoặc nhiều như vại, đối vs `config('define.posts.limit_rows')` cũng đâu cần ngoặc `()` bao ngoài nó đâu

2018-02-04 17:39 UTC, at-huenguyen commented on tests/Browser/Pages/Backend/Posts/AdminListPosts.php
> +                ->visit('/admin/posts?page='.ceil((self::NUMBER_RECORD_CREATE + 1) / (config('define.posts.limit_rows'))));
cmt tương tự dòng 98

2018-02-04 17:39 UTC, at-huenguyen commented on tests/Browser/Pages/Backend/Posts/AdminListPosts.php
> +                ->assertQueryStringHas('page', ceil((self::NUMBER_RECORD_CREATE + 1) / (config('define.posts.limit_rows'))));
cmt tương tự dòng 98

2018-02-04 17:39 UTC, at-huenguyen commented on tests/Browser/Pages/Backend/Posts/AdminListPosts.php
> +class AdminListPosts extends DuskTestCase
Sai convention nhá. Add 1 line nhá

2018-02-08 02:23 UTC, at-huenguyen commented on tests/Browser/Pages/Backend/Posts/AdminListPosts.php
> +        $employeeCode = $users->pluck('employ_code')->toArray();
biến này ko dùng, remove đi nha em

2018-02-08 07:14 UTC, ghost approved these changes

2018-02-08 07:14 UTC, merged