Delete post and this relationship
AT-PHPIntership/flappy-book pull request #99
Opened 2018-01-29 10:51 UTC by at-caonguyen

## Description
Delete post and this relationship
## Reference Requirements
- Product Backlog ID: PBI-11
- Task ID: #11.3

## Reference Isuees
#{issue_id}

## Migrations
NO

## Impacted Areas in Application
List general components of the application that this PR will affect:

- resources/lang/en/posts.php 

## SQL query and `explain`
List of all queries and attach the result of each explaining query (in text, screenshot...)

- delete from `likes` where `likes`.`post_id` = '2' and `likes`.`post_id` is not null
![image](https://user-images.githubusercontent.com/33854530/35506651-99009188-051c-11e8-9a97-1d1c218795d9.png)
- update `comments` set `deleted_at` = '2018-01-29 10:41:27', `updated_at` = '2018-01-29 10:41:27' where `comments`.`commentable_id` = '2' and `comments`.`commentable_id` is not null and `comments`.`commentable_type` = 'post' and `comments`.`deleted_at` is null
![image](https://user-images.githubusercontent.com/33854530/35506712-ce2a91b0-051c-11e8-954f-c3d6f981b56c.png)
- update `posts` set `deleted_at` = '2018-01-29 10:41:27', `updated_at` = '2018-01-29 10:41:27' where `id` = '2'
![image](https://user-images.githubusercontent.com/33854530/35506735-e9a16162-051c-11e8-8d14-2aea72f6371e.png)

2018-02-05 08:47 UTC, ghost reviewed
LGTM

2018-02-06 01:52 UTC, ghost requested changes
Check comment vs nha!

2018-02-06 01:52 UTC, at-nhuibo commented on resources/views/backend/posts/index.blade.php
> +                      <td><a href="{{ route('posts.show', [$post->id, 'page' => $_GET['page'] ?? 1]) }}">{!! Str::words($post->content, config('define.posts.size_short_content'),config('define.posts.
Không được sử dụng `$_GET` vs `$_POST` thuần của PHP nha, vì nó ko an toàn và bảo mật kém.
Dùng `request('page')` của Laravel á.

2018-02-06 01:52 UTC, at-nhuibo commented on resources/views/backend/posts/show.blade.php
> +            <form method="POST" action="{{ route('posts.destroy', [$post->id, 'page' => $_GET['page'] ?? 1]) }}">
`$_GET` này cũm vậy.
À, ở chỗ list ko có nút delete hả? vào detail mới delete đc thôi hay sao?

2018-02-06 01:56 UTC, at-caonguyen commented on resources/views/backend/posts/show.blade.php
> +            <form method="POST" action="{{ route('posts.destroy', [$post->id, 'page' => $_GET['page'] ?? 1]) }}">
Dạ trong list post không có nút edit với delete đó anh

2018-02-06 03:57 UTC, ghost approved these changes
LGTM. Thanks.

2018-02-06 03:57 UTC, merged